In [90]:
import pandas as pd

df = pd.read_csv("training_data.csv", encoding="utf-8")
df.columns = ['content', 'target']

df.head()

                                             content  target
0  anya scan imag comput school project scan imag...       2
1  anya scan imag comput school project imag comp...       3
2  anya scan imag comput school project one colou...       1
3  anya scan imag comput school project anya made...      24
4  bingwen comput come oper system util softwar d...      17

In [91]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['target'])

df['target_encoded'] = le.transform(df['target'])
df.head()

                                             content  target  target_encoded
0  anya scan imag comput school project scan imag...       2               1
1  anya scan imag comput school project imag comp...       3               2
2  anya scan imag comput school project one colou...       1               0
3  anya scan imag comput school project anya made...      24              23
4  bingwen comput come oper system util softwar d...      17              16

In [92]:
from sklearn.model_selection import train_test_split

x = df['content']
y = df['target_encoded']

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)
print(len(x_train), len(y_train))
print(len(x_test), len(y_test))

1068 1068
356 356

In [93]:
from sklearn.feature_extraction.text import CountVectorizer

# instantiate the vectorizer
vect = CountVectorizer()
vect.fit(x_train)

# from sklearn.feature_extraction.text import TfidfVectorizer

# # Replace CountVectorizer with TfidfVectorizer
# vect = TfidfVectorizer(max_features=5000)
# vect.fit(x_train)

x_train_dtm = vect.transform(x_train)
x_test_dtm = vect.transform(x_test)

In [94]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train_dtm, y_train)
y_pred = model.predict(x_test_dtm)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2%}")

Accuracy: 81.46%

In [95]:
import pickle

with open('tf_idf.pkl', 'wb') as f:
    pickle.dump((vect, model, le), f)

In [96]:
from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Encode
encoder = SentenceTransformer('all-MiniLM-L6-v2')
print("Yes")
x_train_encoded = encoder.encode(x_train.tolist(), show_progress_bar=True)
x_test_encoded = encoder.encode(x_test.tolist(), show_progress_bar=True)

# Train
clf = LogisticRegression(max_iter=10, C=1.0)
clf.fit(x_train_encoded, y_train)

# Evaluate
y_pred = clf.predict(x_test_encoded)
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2%}")

Yes

Batches: 100%|██████████| 34/34 [00:08<00:00,  4.11it/s]
Batches: 100%|██████████| 12/12 [00:03<00:00,  3.49it/s]

Accuracy: 72.47%

/home/haorong/Documents/alp/.venv/lib64/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(